name: CI/CD Pipeline for Angular Project

on:
  push:
    branches:
      - master  # Cambiado de "main" a "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Node.js (instalar Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # O la versión que estés usando

    # 3. Instalar dependencias de Angular (npm install)
    - name: Install dependencies
      run: npm install

    # 4. Construir la aplicación (si es necesario)
    - name: Build Angular app
      run: npm run build

    # 5. Desplegar en el servidor
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        # Crear el directorio .ssh en el entorno de ejecución
        mkdir -p ~/.ssh
        # Escribir la clave privada en el archivo id_rsa y asignar los permisos adecuados
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Agregar la clave pública del servidor al archivo known_hosts para evitar problemas con SSH
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        # Crear el directorio de despliegue en el servidor remoto
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $DEPLOY_PATH"
        # Usar rsync para transferir los archivos
        rsync -avz --delete --no-t --exclude 'tests' --exclude '.git' ./ $USERNAME@$HOST:$DEPLOY_PATH
        # Instalar dependencias de producción en el servidor remoto
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && npm install --production"
        # Reiniciar el servicio Apache en el servidor remoto
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl restart apache2"
